### ISSUE TITLE
VR splitscreen is very small on some phone

### ISSUE THREAD

**Issue by mjsibbald** [googlesamples/cardboard-java#24]
So I've tested the SDk on a bunch of  phones now, and the VRmode adjust accordenly to the resolution. 
So on large screens you will see more black than on others. Makes sens. Cause it will fit the cardboard. 

But on for example an Vivo x510t, the VRmode show a very small splitscreen. And a lot of black space. 
Doesn't make any sense. 

Specs:
- 1920 / 1080.

Could somebody tell me why it's so small? I think this is a bug related hardware?
BTW when its not in VRmode, its using all of the space, and show exactly what is expected.

**Comment by smdol** [comment]
This big is caused by certain phones that report an incorrect DPI value.  The DPI is used with the resolution to compute the size of the phone screen in mm, which of them used to compute the projection matrix and viewport for rendering.  An incorrect DPI therefore makes the phone seem to be bigger or smaller than it really is, which leads to this effect.

**Comment by smdol** [comment]
Hm.  Sorry for the typos.  big = bug, which of them = which is then.

**Comment by mjsibbald** [comment]
Yeah I figured that part out. But thanks for confirming. Is there any fallback for these situations?

Thanks!

**Comment by smdol** [comment]
At the moment, there is no good fallback.  Phones that do this are like phones that do not have a gyro: unsuited for use in Cardboard.  There is a hacky fallback for users who are savvy, which is to customize a QR code so that their viewer measurements are scanned the same as wrong DPI / right DPI.

**Comment by mjsibbald** [comment]
Hey Thanks!
This one does have a gyroscope (Vivo x510t) Chinese phone. 
I think I know what you are saying with the qrcode.

**Comment by moneytoo** [comment]
Same issue here (?), with Lenovo Vibe Z2 Pro (model: K920, device: kingdom_row). It used to work just fine but I'm not sure if it was when I still was on KK or running older version of Cardboard. I don't notice any difference when editing ``ro.sf.lcd_density``. 

![device-2015-07-23-200511](https://cloud.githubusercontent.com/assets/1071643/8858223/8e38fed8-3176-11e5-9415-84445de1ff1c.png)

**Comment by h0man** [comment]
Same issue here with OnePlus Two just out of the box and i have no idea how to fix it..
![screenshot_2015-08-21-16-44-11](https://cloud.githubusercontent.com/assets/13905774/9412004/b499a89c-4829-11e5-8ceb-f01039433ce3.png)

**Comment by smdol** [comment]
The usual cause of this is that the DPI reported by the phone does not match reality.  This throws off the calculation of the physical size of the phone, making the Cardboard SDK think the phone is bigger or smaller than it really is.  (In this case, bigger.)  There's currently no software workaround, unfortunately.  As a hack, some users have gone to the Cardboard profile generator site and made their own custom QR codes with scaled physical dimensions to compensate.

**Comment by h0man** [comment]
Thanks @smdol for the quick response ! I'll try that !

**Comment by moneytoo** [comment]
I waited for an fw update for Lenovo K920 (K920_S271_150907_ROW) which I received but the issue is still there. It's device sold in Europe via official channels, it contains Google apps so I believe it passed all the Google compatibility/certification tests. 
Are vendors required to define/report real physical device screen size? Is there such thing in Android compatibility definitions or tests? Why did you for sake switch to something that you (or anyone else) even can't ensure (is that xdpi/ydpi?).
Do you expect end users to generate their QR code? I know resolution, physical size, PPI etc of my device but I find it need lots and lots tries to find out the best values. Tell me what should I put there if it's so easy.

**Comment by moneytoo** [comment]
So I finaly managed to fix it. I had to tweak both reported real DPI and use custom QR to fix vr lens parameters. I may try writing to Lenovo about the DPI but I just hoped you are in better position to iron all things out (and prevent such vendor bugs)...

```
XposedBridge.hookAllMethods(XposedHelpers.findClass("android.view.Display", lpparam.classLoader), "getRealMetrics", new XC_MethodHook() {
            @Override
            protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                DisplayMetrics dm = (DisplayMetrics) param.args[0];
                dm.xdpi = dm.ydpi = dm.xdpi * 3.0f;
                param.args[0] = dm;
            }           
        });
```

**Comment by smdol** [comment]
I'm just as surprised that phones can get away with reporting bogus xdpi/ydpi values, as those are supposed to be the physical pixel size.  There's no other way I know of to calculate the size of the screen in mm from software.  (If anyone one knows one, which isn't also subject to manufacturer-specified inaccuracies, let us know.)

**Comment by barak066** [comment]
moneytoo, have you fixed the source files in this git ? if i have lenovo k910 - what values should i change ?

**Comment by D3m0n92** [comment]
- Unity 5.2.0p1

   Android: On some devices Screen.dpi returns more accurate values.



2015-09-18 16:40 GMT+02:00 barak066 <notifications@github.com>:

**Comment by moneytoo** [comment]
@barak066 It's a fix requiring Xposed framework (which requires root and unlocked bootloader). Let's try discussing it more at https://forums.lenovo.com/t5/K-and-Vibe-Z-Series-Smartphones/incorret-display-on-google-cardboard-on-K910-vibe-Z/m-p/2094256/highlight/false#M12040 to make Lenovo notice of the issue.

**Comment by nathanmartz** [comment]
We've worked around getting bad DPI issues, so this should be fixed for now. Please reopen if not.

**Comment by albeirojr** [comment]
This is the QR Code Google Cardboard for Lenovo K910 Vibe Z.  It's only accurate but works.  
![qr code lenovo k910e vibe z](https://cloud.githubusercontent.com/assets/17484528/13337168/f30af64c-dbe7-11e5-92a4-5429a80ce71e.png)

**Comment by moneytoo** [comment]
Still no luck with the new version 1.8 (on Lenovo K920). I did scan the QR code on the Carboard v2 (Cardboard I/O 2015).

**Comment by kapil42319** [comment]
Can anyone share the custom qr code for lenovo k920  for cardboard v2

**Comment by anchak** [comment]
I made it.
![lenovo k910l](https://cloud.githubusercontent.com/assets/16136575/14531070/7a518dbc-0264-11e6-9b76-79319ce9d389.png)

**Comment by Panoktok** [comment]
@anchak thanks for this..may i know what is your settings for this?i am using it for now since i cant find one for my ZTE AXON ELITE...and i just got my bobovr z4...but its not a full screen one...im trying to experiment on the settings for my QR CODE..

**Comment by bd5155716** [comment]
@Panoktok I had the same issue.
If you already fixed it, please let me know.
![1](https://cloud.githubusercontent.com/assets/15129497/15072799/b6e23762-1395-11e6-8f61-c24e4a833318.jpg)

**Comment by SamovarGolden** [comment]
Here is my solution from https://vr.google.com/cardboard/viewerprofilegenerator/
![qr_viewer_profile](https://cloud.githubusercontent.com/assets/1113047/16244821/1b076460-37fe-11e6-9ef9-7fb0c73f4cfc.png)

Some optimizations could be done still, but my eyes already tired.
Here is settings I've use:
45.0
185.0
0.100
0.100
78
73
78
78

**Comment by koubiak** [comment]
Can you provide the phone model and brand? So we can check if we can help.

Thanks

**Comment by SamovarGolden** [comment]
Oh sorry, i though it's tread for Lenovo Vibe Z2 Pro (K920) =)

Will update my post

**Comment by datha13** [comment]
I have a Blu One Life X2. Can anyone help?

**Comment by JTatum95** [comment]
![blu life one x2 qr](https://user-images.githubusercontent.com/22481306/28049187-3f064c78-65bb-11e7-89d1-5278108668cd.png)
QR code for the Blu Life One X2.

**Comment by ketchupmaster987** [comment]
With my  Galaxy J7 V, I have a couple of similar problems. For some apps the view only shows up as 2 small squares like so
![photo on 7-16-17 at 3 01 pm](https://user-images.githubusercontent.com/28378872/28250840-c55db2ea-6a37-11e7-8f48-709c90618d24.jpg)
or there are lines across the viewer
![photo on 7-16-17 at 3 04 pm](https://user-images.githubusercontent.com/28378872/28250864-0af2cef8-6a38-11e7-9947-51fbd208bb72.jpg)
. These 2 problems only happen for certain apps and I don't know how to fix either of them.

**Comment by starkiller343** [comment]
I have a Sarlar 3d VR headset and a T-Mobile Revvl Plus. Could anyone help me? I'm having the same issue where the splitscreen is smaller than it should be. Is there a qr code that will help? Please.

**Comment by starkiller343** [comment]
I have a Sarlar 3d VR headset and a T-Mobile Revvl Plus. Could anyone help me? I'm having the same issue where the splitscreen is smaller than it should be. Is there a qr code that will help? Please.

**Comment by jdduke** [comment]
@starkiller343: Would you mind attaching a screenshot of the problem?

**Comment by FreeWifiInVan** [comment]
The T-Mobile revvle plus has 2 small squares and I don't know how to fix them
