### ISSUE TITLE
GL_REPEAT does not work

### ISSUE THREAD

**Issue by esminis** [googlesamples/cardboard-java#28]
Not sure why but GL_REPEAT does not work for textures(even if size power of two) in onDrawEye, even on sample app. When rendering looks like it is simply GL_REPEATE is ignored and GL_CLAMP_TO_EDGE is used.

After more investigation I have tracked where the problem is looks like somehow textures get mixed up - if I use GLES20.glActiveTexture(GLES20.GL_TEXTURE2) then everything is ok, but if I use GLES20.glActiveTexture(GLES20.GL_TEXTURE0) or GLES20.glActiveTexture(GLES20.GL_TEXTURE1) then GL_REPEAT does not work - looks that somehow cardboard sdk uses texture0 and texture1

**Comment by R1ck77** [comment]
Hi esminis, 

since I had your same issue, I have investigated the problem, and it looks like that the reason because the textures are not sampled correctly, is that the cardboard SDK developers have used a texture sampler object, and *probably they forgot to unbind it at the start of each stereo renderer callback* (this can be verified by checking the OpenGL trace in a the android monitor).

This is especially confusing, as sampler objects are really OpenGL ES 3.0-only features, but some vendors return OpenGL ES3.0 contexts on ES3-capable devices, even if `setEGLContextClientVersion (2)` is specified (or at least this is true for Qualcomm), as it *might be permitted by the method definition*.

To be frank, I think *behavior can be seriously categorized as a bug*, as the sampler object will be used even if the app is created with OpenGL ES2.0 in mind, but running on a OpenGL ES 3.0 capable device (at least a Qualcomm-based one), leaving the app developer no easy way to work around the issue (there is no `glBindSampler` in `GLES20`...).

A temporary work around for you could be: 

1. if you are doing OpenGL ES3.x, just be aware of the currently bound sampler, and handle your opengl state accordingly
2. if you are doing OpenGL ES2.x things get  more complicated: you have to check if your current context is really a OpenGL ES3.x context and, only in that case, use some `GLES30` functions to turn the sampler object(s) on and off.

Of course this will be required only until the cardboard developers will have fixed the issue (which IMHO would mean unbinding them correctly at the start of each `StereoRenderer` callback, turning them nicely invisible...).

Hope this helps,
Riccardo

**Comment by esminis** [comment]
I can confirm - I get ES3.x context instead of ES2.x and sampler object is bound...

Thanks Riccardo for solution. I hope this problem gets fixed

**Comment by oon3m0oo** [comment]
Indeed, when rendering to a context that supports ES3 we use a sampler object, and it wasn't getting cleaned up before calling back to the application.  We'll have a fix in the next release that should properly restore the state.  Thanks for flagging this!

**Comment by dav-cz** [comment]
Closing this issue, since 0.6 update should fix this. @esminis, thanks for the report and please re-open if that's not the case.

**Comment by TheFakeMontyOnTheRun** [comment]
I'm still seeing this effect on one eye - and I'm using the lastest version. What should I look after to fix?
